name: Linux
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare The LXDE AND XRDP
        run: |
          sudo apt update
          sudo apt install -y wmaker xterm xrdp
          echo 'root:root' | sudo chpasswd
      - name: NGROK
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O n.tgz
          sudo tar -xvzf n.tgz
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          ./ngrok authtoken 2jbbOGMukoFLluOQCHwMt5UbCxY_51bhi9wCuxcNwxzhTmrgb
      - name: Final
        run: |
          sudo service xrdp start
          sleep 10
          ./ngrok tcp 3389
          sudo apt -f install
          SECONDS=0; while true; do echo $SECONDS; sleep 1; done
